### ISSUE TITLE
Add check for fzf splits

### ISSUE THREAD

**Issue by hanschen** [christoomey/vim-tmux-navigator#108]
[fzf](https://github.com/junegunn/fzf) is a fuzzy finder that can be used from within vim or from the shell. It uses `Ctrl-K` and `Ctrl-J` by default to navigate up and down the list, but because fzf opens up in a tmux split, these bindings conflict with the bindings of vim-tmux-navigator.

I was wondering if vim-tmux-navigator could check if a tmux split is running fzf (if not by default, I would appreciate if someone could tell me how to modify .tmux.conf to achieve this), and if that's the case pass the keys to fzf rather than switching panes.

**Comment by christoomey** [comment]
Hello @hanschen, thanks for the question. I'm a user (and big fan!) of fzf, but I don't run into this issue as I use the `C-n`/`C-p` bindings to move up and down the fzf list, leaving `C-j`/`C-k` open for pane navigation. I'd suggest giving this a try as `C-n` and `C-p` are very common "next", "previous" mappings and could serve you well in other apps, and solve this immediate issue.

That said, I did take a look to see it would be possible to extend the mappings in tmux-navigator to special case fzf and unfortunately it doesn't seem possible. The reason is that when fzf (specifically the `fzf-tmux` command) is running, the `pane_current_command` is listed as the parent shell (`zsh` or `bash`). Not suer why this is, but it means that we are unable to detect fzf running, at least via the current method using `pane_current_command`, will not work.

Sorry we don't have a better answer here, but hopefully you can make due with `C-n`/`C-p`.

**Comment by hanschen** [comment]
Thanks for the suggestion and for looking into this, @christoomey! I guess I'm used to `C-j`/`C-k` from ctrlp, but I should be able to get accustomed to `C-n`/`C-p` in time.

Thank you for your great work with vim-tmux-navigator!
