### ISSUE TITLE
<C-h> doesn't work in neovim

### ISSUE THREAD

**Issue by bibek22** [christoomey/vim-tmux-navigator#125]
so, everything else work perfectly fine. `<C-h>` just acts like pressing h.  

`bind-key    -T root   C-h              run-shell "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"`
that is the line i have in tmux. and default setting in vim.  
 
When I'm in bare terminal, C-h does work, but not when inside tmux(even with it's default configs). 

What could be the issue?

**Comment by blueyed** [comment]
Which Vim?
Neovim?
Does `:send-keys C-h` from tmux work?
Search the existing issues also, sounds very similar to existing ones.

**Comment by bibek22** [comment]
no. that didn't work.  
Btw, C-h while in shell inside tmux gets me to pane on left, but only inside of neovim, C-h acts like just 'h'

**Comment by christoomey** [comment]
@bibek22 Have you read through [the summary in the readme re: noevim and Ctrl-h](https://github.com/christoomey/vim-tmux-navigator#it-doesnt-work-in-neovim-specifically-c-h)? I'm not certain, but my guess is you're running into that issue.

**Comment by bibek22** [comment]
Awesome. changing the `kbs` description for term as suggested (here) [https://github.com/neovim/neovim/issues/2048#issuecomment-78045837] does it for me. thanks! closing.

**Comment by bibek22** [comment]
Ot of curiosity, is this a issue in neovim? because C-h does work in just bare terminal with `$TERM=rxvt-unicode-256color` and when I hop into tmux, `$TERM` changes to `Screen ...` and the problem.

**Comment by blueyed** [comment]
@bibek22 
As far as I know Neovim is more affected by this, because it uses the terminfo as-is, and Vim does some workarounds.  (for me there's an issue with `sudo nvim` in tmux, because that uses another terminfo for `TERM=tmux-256color` than with my user.

Getting a "h" sounds weird though.

From the last time I've looked it seems to be likely an issue with the upstream ncurses package, which provides those terminfo files.
I've left some additional comment at https://github.com/neovim/neovim/issues/2048#issuecomment-217755170.

**Comment by NielsCodes** [comment]
I just spent hours following the suggestions here and in the linked threads to no avail. Turned out that `m4xshen/autoclose.nvim` was somehow causing this issue. Not necessarily relevant to this thread, but maybe I can save someone from the same frustrations.
