### ISSUE TITLE
Navigation goes to the wrong Vim window

### ISSUE THREAD

**Issue by Sydius** [christoomey/vim-tmux-navigator#137]
I like to run a tmux session with the upper half being vim and the lower half being a shell. I further split the upper half into two vim panes and the lower half into two shell panes, making 4 quadrants.

When I switch out of vim to the shell, it does not pick the closest pane in the lower half but instead picks whichever of the two I was in last (this happens even if I explicitly run the command `TmuxNavigateDown`). So if I was in the bottom-right and switch to the upper-left, running that command puts me in the bottom-right again whereas I expected it to put me in the bottom-left.

Similarly, switching from the shell panes to vim puts me in whichever vim pane I was in last rather than the one I expect. So if I was in the upper-left and switch to the bottom-right and then execute `select-pane -U`, it puts me in the upper-left whereas I expected it to put me in the upper-right.

**Comment by deimyts** [comment]
I'm experiencing this as well. I think this is the default behavior even when not using `vim-tmux-navigator`. Without the plugin, this behavior is actually pretty useful. With it, though, it is counterintuitive.

For example, given the following layout:
```
| tmux1 | vim1 | vim2 |
``` 
There are 2 tmux panes. The left pane is a shell. The right pane has a vim session with a vertical split. 

**Expected behavior:**
Starting in `tmux1`, pressing `Ctrl+L` repeatedly should always navigate through all panes, in order, from left to right, then loop back to the first pane and do it again.  That would produce the following order: `tmux1` > `vim1` > `vim2` > `tmux1` > `vim1` > `vim2`...etc.

**Actual behavior:**
Starting in `tmux1`, pressing `Ctrl+L` repeatedly navigates through panes in the following order:
`tmux1` > `vim1` > `vim2` > `tmux1` > `vim2` > `tmux1` > `vim2` > `tmux1`...etc.

That is, you are able to navigate through all panes on the first pass only. On the second pass and after, the middle pane (`vim1`) will always be skipped.

**Comment by yangmillstheory** [comment]
Is this intentional? The lack of a reply makes me wonder if it is?

**Comment by yangmillstheory** [comment]
By the way, this is the default behavior (using default vim and tmux bindings).

**Comment by christoomey** [comment]
@yangmillstheory as you pointed out, this is the default behavior of Vim and tmux, and this plugin currently doesn't try to alter that behavior. We've had https://github.com/christoomey/vim-tmux-navigator/issues/70 for a while now with notes on how we might support the more complex version, but we've not yet made any headway on that. I'm going to close this now as #70 better sums up the current state of things, but please feel free to comment or re-open if you think I missed something.

**Comment by yangmillstheory** [comment]
Thanks @christoomey for your work here.
