### ISSUE TITLE
Moving between Vim panes, within a Tmux session

### ISSUE THREAD

**Issue by mascip** [christoomey/vim-tmux-navigator#15]
When I'm only using Vim, without Tmux, then I can use `<C-h>`.
When I'm using Vim from withing a Tmux pane, that I can move to another Tmux pane by using `<C-h>`.

But when I have several Vim panes, within a Tmux pane, then `<C-h>` will move to the nearest Tmux pane, while I would want it to move to the closest Vim pane. To move between Vim panes, I have to use `<C-w>h`. Is there any way we could detect whether there is a Vim pane at the left of the current pane, and then do VimNavigate() instead of a TmuxNavigate(), in this case?

**Comment by tkossak** [comment]
I have the same problem under Cygwin x86 (Win7x64) and Tmuxa 1.9a. The commands don't work in Vim at all. Tmux never sends the key combinations to vim because variables ```#{pane_current_command}``` and ```#{pane_title}``` do not work as expected.

```#{pane_current_command}``` has always value "bash" and it never changes, no matter if i run vim (or any other app) in current pane or not.

```#{pane_title}``` has always value "~", or whatever folder that i ran tmux from and it also never changes, no matter what app/folder is running in current pane.

I noticed that the variable ```#{pane_pid}``` is different for every pane, and it keeps the PID of bash command running in current pane (no matter if vim is the foreground process or not). I tried to use this PID to get children process of this PID and check if one of them is vim, but i couldn't get the script to work so far. I'll try more later.

**Comment by rosshadden** [comment]
I got mine working by (I think?) setting a good `TERM` variable.  Instead of using `screen-256color` or `xterm-256color` like everyone on the Internet says, I used `rxvt-unicode-256color` (which is my actual terminal).

**Comment by oblitum** [comment]
Not sure what happened, it has always been working for me on Ubuntu, but now switching between panes on vim stopped working.

**Comment by oblitum** [comment]
I just checked what happened. In my machine I load vim from a script to load a different vimrc file, it's a one-liner called `vim-for-python3`. When I execute this shell script that in itself just calls vim this tmux configuration doesn't work:

```
# Smart pane switching with awareness of vim splits
is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
```

Because it matches raw vim commands solely...

Maybe using an alias can solve my problem.

**Comment by patrickdepinguin** [comment]
I bumped into this same problem and acknowledge the findings by @oblitum : starting vim through a wrapper (not an alias) causes the moving between vim splits to fail. If the wrapper is a shell script, the output of pane_current_command is 'sh' (or 'bash').

**Comment by rosshadden** [comment]
Just an update for people in case it helps.  I had thought my workflow was solid until I started running vim with `vim --servername foo` in some situations.  This changes the ` - VIM` at the end of the pane title to ` - foo`, and thus broke my previous solution which was simply looking at `#T`.  After experimenting with my config, this is what I came up with:

```sh
isVim="tmux display -p '#{pane_current_command} #T' | grep -iqE '(vim|VIM)'"
bind -n C-j if-shell "$isVim" "send C-j" "select-pane -D"
bind -n C-k if-shell "$isVim" "send C-k" "select-pane -U"
bind -n C-h if-shell "$isVim" "send C-h" "select-pane -L"
bind -n C-l if-shell "$isVim" "send C-l" "select-pane -R"
bind -n C-\ if-shell "$isVim" "send C-\\" "select-pane -l"
```

It works in all of the following cases, which for me covers 100% of my usage:
- `vim`
- `e` - my "edit" alias for the above, which I use more than any other command ever
- `sudo vim` - __most of the solutions people use don't work with this, because `#{pane_current_command}` is just `sudo`!!!__ This is why I have been using `#T` for months
- `se` - my "sudo edit" alias for the above
- `v` - the `fasd` function
- `vim --servername foo` - running `vim` with a servername
- `e --servername bar` - running my alias with a servername

The reason it works is that I am using both `#T` _and_ `#{pane_current_command}`, because __neither of them alone works in all of the above cases__.

I would like for people to try this out and let me know if it works for them.  I have only tested on Arch Linux, using `urxvt` and `tmux 2.1`.  If it works for enough people I'll make a pull request.

**Comment by oblitum** [comment]
@rosshadden there's a lot let unexplained in those changes, like, why go from `is_vim` to `isVim` and why change the regex since what should matter from what you said is just the former part of the command. Your new regex looks a bit broad.

**Comment by rosshadden** [comment]
That's just the evolution of what I have come up with over the two years I've been using this plugin.  The things suggested by others have never really worked well for me so I have always had to experiment and change things to get my setup to work.

In terms of your specific questions, `is_vim => isVim` is simply to align with my own bash style, and can be disregarded.  The regex patterns suggested by the docs and by others have not worked for certain situations in the past, and unfortunately I forget what they were.  I have been participating in this issue for about a year and a half now! :-D.

I will say that in summary, the main ideas in my post are the two things I put in bold.  If you just take those into account you can likely improve your situation.  I am finally happy with every single situation I have encountered, and just want to share that bliss with people in this issue.  Let us know what your config is based on my post!

**Comment by chenoweth** [comment]
@rosshadden I copied your code inside my ~/.tmux.conf, disabled the old code by commenting it, quitted tmux, killed the server `killall tmux`, launched a new session, tried to edit a file with the fasd wrapper by typing `v vim` (which on my machine results in vim ~/.vimrc), splitted the window by typing `:sp`, and finally tried to switch between the two splits with the default keybindings <C-j>, <C-k>, and it doesn't work.

Tested on various terminals : guake, xfce4-terminal and xrvt.

**Comment by rosshadden** [comment]
@chenoweth What is the result of `display -p '#{pane_current_command} #T'` in the tmux console (`prefix+:` by default)?

**Comment by chenoweth** [comment]
@rosshadden On my system, when vim is launched by fasd, the result of `display -p '#{pane_current_command} #T'` is `sh ubuntu`.

I suppose `#{pane_current_command}` returns the name of the parent process (shell script) and `#T` returns my hostname. Unfortunately neither of them contains vim, so the grep can't find it.

I'm using xubuntu 14.04, vim 7.4 and tmux 2.0.

**Comment by sergei-dyshel** [comment]
@chenoweth 
You can try my solution I've posted [here](https://github.com/christoomey/vim-tmux-navigator/issues/96#issuecomment-217889425).

**Comment by blueyed** [comment]
There's a PR for this already: #117.

**Comment by blueyed** [comment]
The original issue is about wrapping inside of Vim (see https://github.com/christoomey/vim-tmux-navigator/issues/70, which has some code in Reddit that could be turned into a PR).

**Comment by blueyed** [comment]
I am closing this, since it appears to have been hijacked with different problems and various ways to troubleshoot.
Please see #117 for a more robust way to detect Vim, and #70 for the original issue.

**Comment by vsymguysung** [comment]
I am having this issue with Tmux 2.6 in Cygwin environment.

I followed the check list below from @christoomey 
> The tmux run-shell command is not recognizing that Vim is active. You can check this by running the following at the the tmux command prompt: display-message -p '#{pane_current_command}'. Make sure you are in Vim before going into the tmux command-prompt (you can access the tmux command prompt via <prefix>:.) The result should be 'vim', or 'Vim', or something that matches grep -iqE '(^|\/)vim$'


> The Vim keymaps are being overwritten - You can check this by verifying the current mapping, and where the mapping is defined, for any of the C-hjkl maps. Use :verbose nmap <C-j> to determine this. This should return something like:

Any advice or suggestion would be much appreciated. Thanks.
