### ISSUE TITLE
Why not use Vim's C-W prefix? Seems to work for me.

### ISSUE THREAD

**Issue by markstos** [christoomey/vim-tmux-navigator#193]
It's great to be able the same navigation shortcuts in both Vim and Tmux, but using C-H,J,K,L, as they have pre-existing meanings in Vim and Bash.

It seems natural to use the `C-w` prefix already used by Vim, as people will already use it by muscle memory, and as far as I'm aware, it doesn't conflict with any common `bash` features.

I believe I've implemented this correctly, but considering I haven't found anyone else opting for this, I'm wondering if I've missed something. 

Here's my .vimrc:

```
let  s:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-w>h :TmuxNavigateLeft<cr>
nnoremap <silent> <c-w>j :TmuxNavigateDown<cr>
nnoremap <silent> <c-w>k :TmuxNavigateUp<cr>
nnoremap <silent> <c-w>l :TmuxNavigateRight<cr>
nnoremap <silent> <c-w>\ :TmuxNavigatePrevious<cr>
```

And .tmux.conf:

```
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-w switch-client -T VIMWINDOWS
bind-key -T VIMWINDOWS h if-shell "$is_vim" "send-keys C-w h"  "select-pane -L"
bind-key -T VIMWINDOWS j if-shell "$is_vim" "send-keys C-w j"  "select-pane -D"
bind-key -T VIMWINDOWS k if-shell "$is_vim" "send-keys C-w k"  "select-pane -U"
bind-key -T VIMWINDOWS l if-shell "$is_vim" "send-keys C-w l"  "select-pane -R"
bind-key -T VIMWINDOWS \ if-shell "$is_vim" "send-keys C-w \\" "select-pane -l"
```

The only slightly novel part of the solution is using a new "VIMWINDOWS" key table that allows defining some Tmux commands with the "C-w" prefix.

If this option is useful, it might make a nice addition to the  README for those who wish to stick with the Vim mappings.

**Comment by markstos** [comment]
OK, so I spoke too soon: Navigation between Tmux panes works with the above, but navigation between Vim windows isn't working at all. I also tried this variation in the `.tmux.conf`. This one is even simpler. It tries to always pass `C-w` through to Vim, but for non-Vim, navigates a Tmux pane:

```
bind-key -n C-w if-shell "$is_vim" "send-keys C-w" "switch-client -T VIMWINDOWS"
bind-key -T VIMWINDOWS h select-pane -L
bind-key -T VIMWINDOWS j select-pane -D
bind-key -T VIMWINDOWS k select-pane -U
bind-key -T VIMWINDOWS l select-pane -R
```

Oh, and the "previous window" syntax doesn't work at all. 

Is there a technical reason why using a "Control-W" prefix can't work? It seems like with Tmux's "key table" support, this should be possible.

**Comment by christoomey** [comment]
Hi @markstos, to answer the first question of "Why not use C-h", it's half history and half preference. This plugin began life as a packaging up [Mislav's gist](https://gist.github.com/mislav/5189704), and in that he used `C-h|j|k|l` rather than `C-w j` and the other Vim navigations. Beyond that, my reason for not changing was convenience. I like the ease of moving across multiple windows by holding down Ctrl and then pressing `lll` or similar without needing a prefix sequence for Vim or tmux. The goal was to blend tmux and vim into one seamless experience, so the less keys the better, and I feel no strong need to tie the mappings to existing Vim mappings.

As to the configurations you're suggesting, I'm not sure exactly what the issues are that you're running into. The one thing that does stand out is `s:tmux_navigator_no_mappings`. The `s:` prefix there will not work (`s:` means "script local", so local to your vimrc in this case). You need to use `g:tmux_navigator_no_mappings` to make a "global" scoped variable.

Lastly, while I certainly appreciate the effort here and your willingness to share back, I don't think this belongs in the README just yet. In the almost four years I've been maintaining this plugin you're the first person I've encountered who wants to use it with the Vim mappings (I'm sure there are other folks with the same idea, I've just not encountered them). Hopefully you're able to figure out the configuration, and if you do please comment back here, but I think we can keep the discussion to this issue rather than adding to the README which already has a ton of detail for a plugin that is intended to "just work".

**Comment by blueyed** [comment]
For the record: <kbd>Ctrl</kbd>-<kbd>w</kbd> deletes a word in Bash/Zsh/readline, so would also conflict with default behavior.

> without needing a prefix sequence for Vim or tmux

At least with tmux you can have mappings that can be repeated, with needing the prefix only once.

E.g. `bind-key -r -T prefix       M-Left            resize-pane -L 5` allows to use <kbd>Alt</kbd>-<kbd>Left</kbd> alone after having it used with the prefix once.

The `repeat-time` option is used to define the timeout in ms for this.  I have `set-option -g repeat-time 1000`.

I actually like this a lot, and think that it actually could become the new recommended config:
```tmux
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -r h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -r j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -r k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -r l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
```

It also works in copy-mode then by default, whereas I had to use the following before:
```tmux
bind-key -r h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -r j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -r k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -r l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
# bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
# Also bind it in copy-mode (needs both: https://github.com/tmux/tmux/issues/1195).
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode    C-h select-pane -L
bind-key -T copy-mode    C-j select-pane -D
bind-key -T copy-mode    C-k select-pane -U
bind-key -T copy-mode    C-l select-pane -R
```

As for selecting the previous pane I am using the following:
```tmux
bind-key ^ select-pane -l
```

**Comment by JoyceBabu** [comment]
I too like the `C-[hjkl]` mapping. Only inconvenience is that `C-h` is a very convenient key mapping for `<backspace>` that works across programs. Re-using the mapping in tmux prevents it from working in `zsh`.

Is there any way to detect and disable the mapping when zsh is in command mode of `vi` editing mode? Or configure zsh to run `tmux select-pane -L`, when pressing `C-h` in command mode?

**Comment by markstos** [comment]
Before I unsubscribe from this, I'm just noting that I gave up on Vim/Tmux integration. I replaced most uses of Tmux with a tiling window manager, Sway. I just use separate navigation commands for Sway and Vim and they work reliably. I suppose I could script my Sway bindings to send "<Ctrl-W> l" instead of "<Super> l" if the current window is NeoVim but haven't tried.
