### ISSUE TITLE
Navigate between vim and tmux splits with C-w

### ISSUE THREAD

**Issue by JPFrancoia** [christoomey/vim-tmux-navigator#199]
Hi,

In vim, I actually never use <C-w><C-h> (h, j, k or l) to navigate between splits. I always use <C-w><C-w>, which simply rotates through the split. I don't need anything else since I rarely have more than 2 splits. I just remaped <C-w><C-w> to <C-w>, because it's shorter to type.

I'd like to rotate(scroll) through tmux and vim splits at the same time using <C-w>. Do you think it's possible ?

Best

**Comment by christoomey** [comment]
Hi @JPFrancoia, in theory you could use a similar technique to the plugin where you bind the key in tmux to behave differently based on whether or not Vim is active. That said, I think you might run into some issues trying to make the "rotate" bit work properly when you go back from tmux to vim as the previous Vim pane will be on the unexpected side.

Hopefully that helps, but unfortunately I don't think I can provide much more. Since this is not an issue with the plugin and not something I expect we'll want to add support for, I'm going to close this issue now.
