### ISSUE TITLE
status bar/location list etc in vim sporadically cause line differences

### ISSUE THREAD

**Issue by tonywoode** [christoomey/vim-tmux-navigator#214]
when moving UP/DOWN between tmux shell (zsh) and vim (mvim 8.1) panes. 
...when vim is in the top window, 
...often , a visible line shift occurs, such that, when moving back UP to vim, what is rendered on screen is one line different from where the cursor thinks it is, a vim screen refresh doesn't cure it, a `:redraw!` cures it
This seems to happen where there is any kind of informational line commanded to be at the bottom of vim, for instance any kind of status bar. But it doesn't always happen, perhaps 50% of the time.
This makes hjkl navigation pretty much impossible for me, as I end up overwriting text on the wrong line of a vim-in-tmux pane, and fiddling about to redraw, more than negating any benefit of the keyboard shortcuts
Any tips?

**Comment by christoomey** [comment]
Hi @tonywoode, sorry to hear about the trouble. I'd be surprised if the plugin itself were the culprit here as it does little beyond dispatching navigation commands. That said, hopefully we can figure out the source of the issue. Some questions:

- Is it only the Vim window that gets messed up?
- Does running `:redraw!` in the Vim window fix the issue?
- Is there any output from `:verbose autocmd FocusGained`?

My guess is that there is some action happening when you reenter Vim that is blocking for a moment, and in that time any other keys are misinterpreted. Let me know what you find with the above questions.

**Comment by tonywoode** [comment]
Thanks!
 >   Is it only the Vim window that gets messed up?
YES
 >   Does running :redraw! in the Vim window fix the issue?
YES
    Is there any output from :verbose autocmd FocusGained?
```
--- Auto-Commands ---
FocusGained
    *         if mode() != 'c' | checktime | endif
        Last set from ~/.vimrc
```

I think I see where you're going here - append a redraw command to FocusGained?

**Comment by tonywoode** [comment]
commenting out the line mentioned above from my vimrc doesn't change the issue

**Comment by tonywoode** [comment]
yes the redraw cures it, thanks for pointing me in the right direction!
