### ISSUE TITLE
Can't Ctrl-j or Ctrl-k out of a terminal spawned from Vim

### ISSUE THREAD

**Issue by raw-bin** [christoomey/vim-tmux-navigator#226]
Wasn't able to figure out whether this is expected behaviour hence the Issue. Apologies in advance if applicable.

If I split out a vertical terminal from within Vim by invoking `:vertical terminal` then I find that I cannot now use my beloved Ctrl-{j,k} key binds to navigate tmux panes or vim splits as I normally can. The only way to break out of the vim terminal is to exit out of it.

Any help appreciated.

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 05 2018 21:42:14)
tmux 2.7
Ubuntu 18.10 x86_64
tmux-navigator plugin installed via vim Plug (currently points to commit 9f7d1588b04644d8a1671d2325fefbb4f772e466)

**Comment by raw-bin** [comment]
Come to think of it - I can do without vim's internal terminal and just rely on tmux to split out a terminal on demand - one that I can continue to Ctrl-{j,k} out of as always.

So my question is kind of redundant and I'm happy.

However, I'm intrigued as to why the Vim internal terminal kind of captures the key binds so will leave this open in the hope that I get an answer at some point. No biggie. Thanks.

**Comment by christoomey** [comment]
I'm less familiar with the Vim terminal as I prefer to use tmux to split terminals, rather than have terminals in Vim (which is in tmux). That said, my understanding is that with neovim there is a terminal-specific mode and terminal specific mappings, so you would need to map in there. I believe this issue is related: https://github.com/christoomey/vim-tmux-navigator/pull/217.

Hope that helps. I'm going to close this now as I don't believe there is anything wrong from the plugin's perspective, but please feel free to comment or reopen if you think I missed something.
