### ISSUE TITLE
Ctrl-L maps to refreshing screen rather than moving pane

### ISSUE THREAD

**Issue by Steve-Tod** [christoomey/vim-tmux-navigator#251]
Hi, thank you for your useful tool!

I use **tmux** in **zsh**. I use your default settings in .tmux.conf file. However, in a new ubuntu machine, the Ctrl-L maps to refreshing screen rather than moving to right pane. Is there any solution? Why does this happen?

**Comment by christoomey** [comment]
Hmm, not sure what the cause would be. It sounds like your mapping may not be taking, or might be overridden by something else.

You can check what the current mapping is by running `tmux list-keys` and then scanning the output for entries related to control left (might be listed as `C-l`, or `C-Left` or similar variations.).

**Comment by Steve-Tod** [comment]
The first rows of the output of `tmux list-keys` are as follows. It seems the mapping is taken in tmux but the `C-l` is caught by some other process.
<img width="421" alt="image" src="https://user-images.githubusercontent.com/26958167/75085464-913ce880-5564-11ea-9048-c68c126e9aed.png">

**Comment by madis** [comment]
For me this happened only in `netrw` (https://neovim.io/doc/user/pi_netrw.html). Meaning I could move around in vim splits and tmux panes but couldn't move right from vim split that had `netrw` open. It was because `netrw` had set bindings for `ctrl-l` (https://neovim.io/doc/user/pi_netrw.html#netrw-ctrl-l) and `ctrl-h` https://neovim.io/doc/user/pi_netrw.html#netrw-ctrl-h

I haven't found a good way to fix it. Doing `:unmap <buffer> <C-l>` in `netrw` split made the key shortcut temporarily work (i.e. `ctrl-l` to move to pane on the right). But next time (after going out & re-entering `netrw` pane) it didn't work again.

I'd be interesting to know if you have some solution ideas for this?

**Comment by christoomey** [comment]
I haven't spent much time poking at this, but looking at `:verbose nmap <buffer> <c-l>` in a netrw window I see:

```
n  <C-L>        @<Plug>NetrwRefresh
        Last set from /usr/local/Cellar/vim/8.2.1400/share/vim/vim82/autoload/netrw.vim
```

Digging in a bit more in that file, it looks like `!hasmapto('<Plug>NetrwRefresh')` is checked, so if you were to define your own mapping for that, e.g. `nmap <buffer> <silent> <nowait> <c-e>	<Plug>NetrwRefresh`, then I don't think netrw would map it anymore.

**Comment by cbio-mannyschneck** [comment]
> I haven't spent much time poking at this, but looking at `:verbose nmap <buffer> <c-l>` in a netrw window I see:
> 
> ```
> n  <C-L>        @<Plug>NetrwRefresh
>         Last set from /usr/local/Cellar/vim/8.2.1400/share/vim/vim82/autoload/netrw.vim
> ```
> 
> Digging in a bit more in that file, it looks like `!hasmapto('<Plug>NetrwRefresh')` is checked, so if you were to define your own mapping for that, e.g. `nmap <buffer> <silent> <nowait> <c-e> <Plug>NetrwRefresh`, then I don't think netrw would map it anymore.

Thank you for being an awesome maintainer!

**Comment by pencilcheck** [comment]
Doesn't work, I even put it inside vim/ftplugin/netrw.vim and all it did is make a new mapping instead of replacing the old one, so C-l still maps to refresh for me.

I'm on neovim.
