### ISSUE TITLE
Same binds, but ignore tmux while I'm in neovim pane

### ISSUE THREAD

**Issue by IZUHU** [christoomey/vim-tmux-navigator#254]
I've been struggling trying to get this to work the way I want to...I'm not even sure if its possible, but I want the default window splitting binds in neovim `C-w v` `C-w s` `C-w n` to split my windows when I'm in a neovim pane. However the problem is, it triggers tmux pane splitting that also has those same binds. Is it possible to keep my binds the same, but ignore tmux when I'm in neovim ?

There's a weird way to bypass this which involves pressing `C-w` twice in the neovim pane then pressing the key I want to split. That's way too much overhead for my liking....Please help, and my apologies if I'm doing anything wrong....This is my first github post

**Comment by christoomey** [comment]
Hmm, I think you could use a similar trick that this plugin uses. The core idea is that Vim is running inside tmux, so you need to write the tmux mappings such that

- if the current process is Vim, then forward the keystrokes to vim
- Otherwise, handle it in tmux

If you have the [configuration code in your tmux.conf](https://github.com/christoomey/vim-tmux-navigator#add-a-snippet), you can reuse the `$is_vim` check

``` tmux
bind-key -n 'C-w v' if-shell "$is_vim" 'send-keys C-w v'  'split-window -h'
# etc for the other ones
```

I'm going to close this now as this functionality is not something that we'll want to support directly in the plugin, but hopefully the above points you in the right direction.
