### ISSUE TITLE
Check if loaded then set key bindings

### ISSUE THREAD

**Issue by tkolleh** [christoomey/vim-tmux-navigator#275]
I've split up my neovim config file for different systems and sometimes I want to have some plugins disabled. How can I check if vim-tmux-navigator has not loaded and then set key bindings. The following code always prints the `echomsg`, indicating that `TmuxNavigateDown` command does not exist. It does I'm using it.

```vim
if exists(':TmuxNavigateDown')
  " config for vim-tmux-navigator plugin
  " Do not write all buffers before navigating from Vim to tmux pane
  let g:tmux_navigator_save_on_switch = 0

  " Disable tmux navigator when zooming the Vim pane
  let g:tmux_navigator_disable_when_zoomed = 1
else
  " select window splits
  " the following key bindings are the default for the vim-tmux-navigator plugin
  "
  echomsg 'tmux-navigator not here'
  echomsg 'setting window split navigation key bindings'
  nmap <C-h> <C-w>h
  nmap <C-j> <C-w>j
  nmap <C-k> <C-w>k
  nmap <C-l> <C-w>l
endif
```

**Comment by christoomey** [comment]
Assuming you're using VimPlug or pathogen or similar, they typically don't load plugin code until after they process most of the Vimrc, so that explains why the condition you're using is always falling into the `echomsg` branch.

Given the above limitation, I'm not sure this is something that could be solved on the plugin side. Instead, I'd wonder if you might be able to move this code to live alongside where you activate or don't activate the plugin. That way, the activation and configuration can vary together.

Hope that helps. I'm going to close this now as I don't think there is anything specific to this plugin at play here.

**Comment by jandamm** [comment]
I'm using the native package manager.
My setup is like this:

```vim
if has($TMUX)
	packadd vim-tmux-navigator
else
    " Setup non tmux-navigator key bindings
endif
```
