### ISSUE TITLE
Error on Install 

### ISSUE THREAD

**Issue by davidcastilloc** [christoomey/vim-tmux-navigator#291]
In NeoVim 
fatal: could not read Username for.. Is SSH Error keys?

![imagen](https://user-images.githubusercontent.com/14878209/99500213-65faf480-2950-11eb-8482-b6189fc5b441.png)

**Comment by christoomey** [comment]
Hi @davidcastilloc, I don't think that issue is related to anything specific to this plugin. Not sure how you're installing, but that does seem to be a connection issue. Specifically, it's trying to use the https:// download which require your username & password, but since it doesn't have them it attempts to prompt you for them, but the "terminal prompts disabled" message show that that is failing.

Again, not sure what you're using to install, but if that program uses the `git@github.com:...` git URL then your SSH key would be used and everything should work.

Closing this now as I don't believe this is an issue with the plugin, but [here is some additional context](https://ourtechroom.com/tech/https-vs-ssh-in-git/#:~:text=Git%20used%20SSH%20protocol%20to,fetch%20and%20git%20pull%2C%20etc.) to hopefully help you sort it out. Best of luck
