### ISSUE TITLE
Is there any way to set the shortcut keys for copy and paste?

### ISSUE THREAD

**Issue by zhouyangnk** [christoomey/vim-tmux-navigator#292]
Great plugin!  Thank you maintainer!

and I have a small question here, is there any way to set the shortcut keys for copy and paste?
like ctrl [ means tmux's \<prefix\> ctrl [, and ctrl ] means tmux's \<prefix\> ctrl ].

**Comment by christoomey** [comment]
Hi @zhouyangnk, glad you enjoy the plugin! I might be missing something, but I don't believe your question is related to this plugin.

That said, I believe you can achieve the functionality you're looking for with something like the following:

```
# add the following to your ~/.tmux.conf file

bind-key -n C-[ copy-mode
bind-key -n C-] paste-buffer
```

I didn't test those key bindings, but I think they're in the space of what you want.

All that said, I wonder if rather than mapping to those keys, you might be better served by connected [tmux to the system clipboard](https://thoughtbot.com/blog/tmux-copy-paste-on-os-x-a-better-future).

I'm going to close this now as I don't believe this question really pertains to this plugin, but hope the above info helps on your search!

**Comment by zhouyangnk** [comment]
Yes, you are right, I can set these shortcuts in .tmux.conf.

Sorry for my careless.
Thank you for your kindly reply.
