### ISSUE TITLE
install plugins but not loaded

### ISSUE THREAD

**Issue by JiuRanYa** [christoomey/vim-tmux-navigator#351]
I install `vim-tmux-navigator` by `tpm`

![image](https://github.com/christoomey/vim-tmux-navigator/assets/58846658/6199f2b7-9aa9-4591-9d48-3701140545c3)

But it doesn't work for me，`:TmuxNavigatorProcessList `

 I guess it not loaded，can you give me some help？

I use neovim， all version ok

**Comment by christoomey** [comment]
You only mention the TPM install -- this will only install the tmux side of things. You also need to install the vim plugin. See https://github.com/christoomey/vim-tmux-navigator#installation for notes.

Going to close this now as I believe that's the issue here, but feel free to comment if that doesn't resolve things.

**Comment by youzhaing** [comment]
Thanks a lot for your replay!

**Comment by JiuRanYa** [comment]
> You only mention the TPM install -- this will only install the tmux side of things. You also need to install the vim plugin. See https://github.com/christoomey/vim-tmux-navigator#installation for notes.
> Is
> Going to close this now as I believe that's the issue here, but feel free to comment if that doesn't resolve things.

Thanks a lot for your replay. I thought only need to install tmux side of things. Problem have been solved.
