### ISSUE TITLE
Cannot navigate between Neovim windows when in tmux session.

### ISSUE THREAD

**Issue by amin-farjadi** [christoomey/vim-tmux-navigator#424]
## Status

* Does not work
  - Navigating between Neovim windows in tmux
* Works
  - Navigating between tmux panes
  - Navigating between Neovim windows outside of tmux

## System

* OS: MacOs 15.1.1
* Terminal: iTerm2
* Tmux: 3.4
* Vim: Neovim 0.10.1

## Neovim (in tmux)

* Plugin manager: Lazy
* `:TmuxNavigatorProcessList` -> `Ss+  zsh (qterm)`
* `:! echo $TMUX` -> `/private/tmp/tmux-502/default,4816,0`
* `:verbose nmap <C-h>`
```
      n  <C-H>       * :<C-U>TmuxNavigateLeft<CR>
        Last set from ~/.local/share/nvim/lazy/vim-tmux-navigator/plugin/tmux_navigator.vim line 19
```

## Neovim (no tmux)

* `:TmuxNavigatorProcessList` -> `E 492: Not an editor command`
* `:! echo $TMUX` -> empty
* `:verbose nmap <C-h>`
```
      n  <C-H>       * :<C-U>TmuxNavigateLeft<CR>
        Last set from ~/.local/share/nvim/lazy/vim-tmux-navigator/plugin/tmux_navigator.vim line 19
```

**Comment by christoomey** [comment]
A couple of things based on what you shared:

- The `E 492: Not an editor command` is due to the lazy config not having `'TmuxNavigatorProcessList'` -- I just updated the example config with a fix for that (see [this commit](https://github.com/christoomey/vim-tmux-navigator/commit/d847ea942a5bb4d4fab6efebc9f30d787fd96e65)).
- Your tmux process list does not look to contain any vim process. I'm not sure what to make of that, but that's definitely the issue.

**Comment by amin-farjadi** [comment]
`E 492: Not an editor command` still persists outside of a tmux session despite the change to Lazy config—the `TmuxNavigatorProcessList` command does not load, other commands load and work fine. 😕 Said command gets loaded in a tmux session.

I will dig around and report back why no vim process can be seen in my tmux session.

**Comment by BriHan-Tech** [comment]
I have a solution to this problem here:

https://github.com/BriHan-Tech/is-vim

**Comment by amin-farjadi** [comment]
Hi @BriHan-Tech,

Excellent, that solved my problem! Thank you very much. Very well documented and explained as well. 🙌
