### ISSUE TITLE
Can navigate from vim to tmux but not back from tmux

### ISSUE THREAD

**Issue by jesseclark** [christoomey/vim-tmux-navigator#62]
Hello, I've installed the plugin using tmux 1.9 and Vim 7.4 on Mavericks. 

I removed any conflicting key mappings from my .vimrc and added the lines to ~/.tmux.conf:
```
 is_vim='echo "#{pane_current_command}" | grep -iqE "(^|\/)g?(view|n?vim?)(diff)?$"'
 bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
 bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
 bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
 bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
 bind -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
```

I can navigate from a vim instance in one tmux pane to another tmux pane but not from a tmux pane at the command line to any other tmux pane, running vim or not. I have tested in OS X Terminal and iTerm. I also tried using the tmux configuration lines from the thoughtbot blog post but that did not help.

Any ideas of what else I should check/change?

**Comment by christoomey** [comment]
Hey @jesseclark, can you confirm that you've checked things in the [troubleshooting section of the readme](https://github.com/christoomey/vim-tmux-navigator#troubleshooting)?

**Comment by jesseclark** [comment]
Hi @christoomey I had tried all the troubleshooting suggestions short of using Mislav's original script and was not getting anywhere. However, my .tmux.conf was generated from the default settings and then I added the tmux-navigator settings at the bottom. I started over with an empty .tmux.conf and added just the above configuration lines to it and everything is working fine now.

**Comment by epwallace** [comment]
For anyone else who might be reading with the same problem, try sourcing your .tmux.conf file from the command line with`tmux source-file ~/.tmux.conf`. If your .tmux.conf file is symlinked to another location, try sourcing the actual file. When I ran the previous line, it didn't raise any errors but I was still unable to use <C-hjkl> from a non-Vim pane. When I ran`tmux source-file ~/dotfiles/tmux.conf` instead, I received some "unknown command" errors. It turns out I had accidentally uncommented a few lines while editing. Everything works after adding back a few hashtags and resourcing the file.
