### ISSUE TITLE
Does not work for vimx.

### ISSUE THREAD

**Issue by kadamski** [christoomey/vim-tmux-navigator#63]
I'm running vimx instead of vim and I had to change grep regex to `grep -iqE "(^|\/)g?(view|n?vim?x?)(diff)?$"` to make vim->vim working.

**Comment by christoomey** [comment]
Hello @kadamski, glad to hear you were able to find a workaround. Unfortunately I can't support every variant of Vim out there so some will have to fall through the cracks. Closing this now as I think vimx is sufficiently rare, but thanks for reporting this in case someone else runs into the same issue.

**Comment by mwcz** [comment]
I just ran into the same problem and discovered the same solution.  Just +1ing this.  `vimx` is used often on Fedora at least here at Red Hat because vimx (from the `vim-X11` package) comes precompiled with X clipboard and mouse support.

Either way *thank you* for vim-tmux-navigator, it's great!

**Comment by christoomey** [comment]
Hey @mwcz, thanks the update and glad to hear the plugin is useful to you.

As an aside, could you check if using an alias `alias vim=vimx` would solve this for you without needing to alter the grep pattern? I just realized that I personally run with the alias `vim='mvim -v'` and it works for me, so that might be a more general solution rather than updating the grep for all the vim* variants out there.

**Comment by mwcz** [comment]
@christoomey I already use that alias, but it doesn't work.  Peculiar that it works for you with `mvim`...  The only explanation I can think of is that `mvim` itself might be an alias to a vim process that does match the regex.  I do agree that matching all vim variants is a headache. :)
