### ISSUE TITLE
Switching from vim to terminal while split pane tmux within the fish shell doesn't work

### ISSUE THREAD

**Issue by JonahMoses** [christoomey/vim-tmux-navigator#77]
![screen shot 2015-06-10 at 9 39 57 am](https://cloud.githubusercontent.com/assets/3462296/8090338/4caa880a-0f62-11e5-8d43-55f788f795a2.png)

**Comment by christoomey** [comment]
Hello @JonahMoses, I've not seen this before. Are you on Windows by any chance? (it is mentioned in the help for `E484`).

My guess is the `system` call is failing and or can't find tmux. Can you test the following in Vim and share the output: `:call system("tmux list-sessions")<cr>` (type the command in Vim command prompt and hit enter).

**Comment by JonahMoses** [comment]
I'm on Mac os 10.10.3, vim 7.3, fish 2.1.2.

when I put ":call system("tmux list-sessions")<cr>" into vim I get "E488: Trailing Characters"

p.s. I've thoroughly enjoyed your plugin and am incredibly astonished how quickly you responded and how helpful you're being! Thank you for being awesome and building awesome things!

**Comment by christoomey** [comment]
My pleasure, and thanks for the kind words. Based on what you're describing I would guess that it has to do with Fish since that is the unknown element for me. Can you compare the following:

- `:echo system("ls")`
- `:echo system("tmux -V")`

Vim needs to be able to talk to tmux for this plugin to work. Have you had success with any Vim + tmux stuff in the past, or is this your first try? It might be that you need to set your shell in Vim to be fish, or that you need to add a PATH entry for tmux into your non-interactive startup file for whatever shell Vim is using.

Try the commands above and let me know what they produce.

**Comment by JonahMoses** [comment]
I've used vim and tmux with zsh before and it worked well. I recently switched to fish.

":echo system("ls")" - lists out the directory I'm currently in.
":echo system("tmux -V")" - 'tmux 1.9a'
These are the responses I get while in vim not within tmux and vim within a tmux session.

**Comment by JonahMoses** [comment]
Just upgraded to vim 7.4.712 and am getting new results:
- when not inside tmux but within vim, I type "echo system('tmux -v')" and I get "open terminal failed: not a terminal"
- when inside tmux and vim, I type "echo system('tmux -v')" and I get "sessions should be nested with care, unset $TMUX to force"

**Comment by christoomey** [comment]
Hello @JonahMoses, not sure what the outside of tmux error is, but for testing within tmux, the `-v` needs to be `-V`. (`-v` is not supported and as such tmux seems to ignore it and try to run the bare tmux command which creates a session. `tmux -V` with the big V is for the version output).

**Comment by JonahMoses** [comment]
@christoomey sorry strictly my fault for not capitalizing the -v, however in my tests I was utilizing -V
