### ISSUE TITLE
Can't bind <ctrl-;> to select-pane -R despite escaping semicolon(s)

### ISSUE THREAD

**Issue by RatanRSur** [christoomey/vim-tmux-navigator#82]
`bind -n C-; if-shell "$is_vim" "send-keys C-;" "select-pane -R"`
In this line, I've tried every combination of escaping and not escaping the two semicolons but the same error always appears on tmux invocation:
`/Users/username/.tmux.conf:19: unknown command: select-pane -R`

Some more details:
OS X Yosemite (10.10)
tmux and vim are the latest versions

**Comment by abair** [comment]
Either of the two semicolons in that statement could be causing the problem.  When I bind `C-;` in tmux, I can't get it to work unless I bind it as `bind -n C-\; ...`, so that's probably your first problem.

As for how you intend to map `<c-;>` in Vim, I'd love to know.  I don't know of a way for this to be done; however, the below is a workaround for the behavior you want.

In .tmux.conf:
`bind -n C-\; if-shell "$is_vim" "send-keys C-w ';;'" "select-pane -l"`

In .vimrc
`nnoremap <silent> <c-w>; :TmuxNavigateRight<cr>`

I'm betting you don't use `<c-w>;` for anything, so that should do exactly what you want :)

Wondering what's up with the `';;'` in the bind command?  If you leave it as just `';'` you'll have to hit `C-;` twice in tmux to get vim to behave correctly.  The first `C-;` will put vim in `<c-w>` mode, and the second `C-;` will send it the `;` needed to execute the command from `<c-w>` mode.  If tmux sends `;;` to vim instead, it'll all happen at once.  I'm not quite sure why it's acting like that at the moment.

**Comment by christoomey** [comment]
Hello @RatanRSur, can you confirm if the above works for you (and thanks @abair for the detailed response!)?

**Comment by RatanRSur** [comment]
Just tried it, it does not seem to work :frowning:

**Comment by abair** [comment]
Can you post the line from your .tmux.conf for us to see?  The error, too, if it's different this time.

**Comment by RatanRSur** [comment]
Sure thing.

`bind -n C-\; if-shell "$is_vim" "send-keys C-w ';;'" "select-pane -R"`

and in vim 

`nnoremap <silent> <c-w>; :TmuxNavigateRight<cr>`

If I manually send `<c-w>;` in vim, then it does the right thing, however, tmux isn't sending that.

There's no error on tmux invocation.

**Comment by RatanRSur** [comment]
Hi @abair @christoomey , any ideas on a workaround for this?

**Comment by christoomey** [comment]
Hi @RatanRSur, please correct me if I'm mistaken, but I think this is more a general tmux question than anything specific to vim-tmux-navigator.

Unfortunately I don't know how (or if) to get the mapping to work. I think you'll likely have better luck in a more general forum like http://stackoverflow.com/questions/tagged/tmux.

I'm going to close this now based on this being a tmux question, rather than vim-tmux-navigator question, but please feel free to reopen or comment if you think there is something specific to vim-tmux-navigator.
