### ISSUE TITLE
Can't switch-pane up or down out of NERDTree.

### ISSUE THREAD

**Issue by mtchllbrrn** [christoomey/vim-tmux-navigator#83]
From a NERDTree split, switching panes left/right works as expected, but attempting to switch up/down doesn't. My binding is Ctrl+h/j/k/l to switch panes, and using Ctrl+j/k from NERDTree just changes lines.

**Comment by christoomey** [comment]
This looks like it is due to NerdTree [setting buffer local mappings for the nerdtree window](https://github.com/scrooloose/nerdtree/blob/0b44415a3302030b56755cc1135ca9ca57dc1ada/plugin/NERD_tree.vim#L117-L119) when you open it. Nothing I can do from `vim-tmux-navigator`, but it looks like the specific mappings are configurable so you could map them to something else.

You can disable with:

``` vim
let g:NERDTreeMapJumpNextSibling = '<Nop>'
let g:NERDTreeMapJumpPrevSibling = '<Nop>'
```

**Comment by mtchllbrrn** [comment]
Good call, that fixed the issue.
