### ISSUE TITLE
Support custom tmux socket

### ISSUE THREAD

**Issue by thejohnfreeman** [christoomey/vim-tmux-navigator#87]
I'm on a shared machine where /tmp is cleaned regularly. I keep my tmux socket in my home directory so that I don't lose the session:

```
$ tmux -S ~/.tmux.socket
```

Every tmux command needs that argument to work:

```
$ tmux select-pane -L
failed to connect to server
$ tmux -S ~/.tmux.socket select-pane -L
# selects pane
```

vim-tmux-navigator does not work in this tmux session until I add the socket parameter in the vim script [here](https://github.com/christoomey/vim-tmux-navigator/blob/master/plugin/tmux_navigator.vim#L56). I'm not too familiar with VimScript. Ideally there'd be a plugin option (or auto-detection if possible) to control the presence and value of the socket parameter. I believe you can add that feature better than I can, or else I'd make the pull request myself. Please?

**Comment by christoomey** [comment]
Hey @thejohnfreeman, this makes sense, but unfortunately it is far enough of an edge case (and not one I experience) that I am unlikely to work on implementing support.

That said, I'd be happy to work with you if you wanted to undertake the dev / documentation effort. I expect this would require:

- Extract a function for all `tmux` commands (currently 2 in the plugin file, search for `system` to find them) to centralize them
- Introduce a `g:vtn_socket` valriable
- Make the `tmux` function from the first step conditionally include the `g:vtn_socket` value if present, otherwise compose a normal tmux command
- Document the `g:vtn_socket` variable.

Please let me know if you have any other questions.
